### ISSUE TITLE
Segmentation fault in libc (using sm rip ext)

### ISSUE THREAD

**Issue by WeSTManCoder** [ErikMinekus/sm-ripext#61]
Stack
#0  0xf7568116 in free () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#1  0xf7562554 in _IO_default_finish () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#2  0xf7554be9 in fclose () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#3  0xf037d8b4 in _nss_files_gethostbyname3_r () from /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
#4  0xf037ddc3 in _nss_files_gethostbyname_r () from /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
#5  0xf75efdab in gethostbyname_r () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#6  0xf75ef56c in gethostbyname () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#7  0xf691f1a3 in NET_StringToSockaddr(char const*, sockaddr*) () from bin/engine_i686.so
#8  0xf691f329 in NET_StringToAdr(char const*, netadr_s*) () from bin/engine_i686.so
#9  0xf698a9b7 in CUploadGameStats::UpdateConnection() () from bin/engine_i686.so
#10 0xf5c91446 in CServerGameDLL::GameFrame(bool) () from /home/pub/cstrike/bin/server_i486.so
#11 0xf144d94a in __SourceHook_FHCls_IServerGameDLLGameFramefalse::Func(bool) () from /home/pub/cstrike/addons/sourcemod/bin/sourcemod.1.ep1.so

My English is terrible. Excuse me.

Sometimes I catch sigsegv when I use your extension. Probably the problem is in the libc6, is it not fixed in the extension itself?
Debian 8

**Comment by WeSTManCoder** [comment]
im using -nodns in start parameter. Sigsegv:

#0  0xf7624248 in rewind () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#1  0xf0443e04 in ?? () from /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
#2  0xf0444e6d in _nss_files_gethostbyname4_r () from /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
#3  0xf768ce28 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#4  0xf768e19b in getaddrinfo () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#5  0xed47f527 in Curl_getaddrinfo_ex (nodename=0xeac02c68 "api.ban.gm-world.ru", servname=0xe898231f "443", hints=0xeac02c1c, result=0xeac02c18)
    at /home/runner/work/sm-ripext/sm-ripext/extension/curl/lib/curl_addrinfo.c:124
#6  0xed47b106 in getaddrinfo_thread (arg=0xeac02bf8) at /home/runner/work/sm-ripext/sm-ripext/extension/curl/lib/asyn-thread.c:306
#7  0xed47fd7e in curl_thread_create_thunk (arg=0xeac02ca8) at /home/runner/work/sm-ripext/sm-ripext/extension/curl/lib/curl_threads.c:57
#8  0xf756cecb in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#9  0xf76a4d0e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6

**Comment by WeSTManCoder** [comment]
problem sovled. error in getaddrinfo function. update glibc
